### ISSUE TITLE
nap-example broken?

### ISSUE THREAD

**Issue by dustindclark** [oehokie/NodeAlarmProxy#4]
@oehokie , correct me if I'm wrong, but it looks like the events that are subscribed to in nap-example.js are incorrect.  According to index.js, the events are "partition", "zone" and "data".  I can submit a PR, but I wanted to make sure that I wasn't missing something.  Events don't appear to fire under "zoneupdate", "partitionupdate", "partitionuserupdate", or "systemupdate".

Also, just to make sure I'm understanding the code correctly, sending a command to envisalink occurs via manualcommand() or getCurrent().  The callback for these events don't include any context.  Instead, the context is included via events.  I would like to see the callback firing only after the message from Envisalink has been received so that the callback includes the response information.

**Comment by oehokie** [comment]
yeah, you're right.  I must've forgot to update it.  You can reference this:  https://github.com/oehokie/SmartDSC/blob/master/NAP-demo/app.js  which uses it correctly

**Comment by oehokie** [comment]
@dustindclark Thanks for the PR!

**Comment by dustindclark** [comment]
No prob.  Thanks for making it easy to integrate with envisalink.

Dustin

Sent from my iPhone

On Jan 16, 2016, at 5:22 PM, Matt Martz <notifications@github.com> wrote:

@dustindclark <https://github.com/dustindclark> Thanks for the PR!

—
Reply to this email directly or view it on GitHub
<https://github.com/oehokie/NodeAlarmProxy/issues/4#issuecomment-172269784>.

**Comment by dustindclark** [comment]
@oehokie, should nodealarmproxy.js be deleted?  Looks like index.js is more current?

**Comment by oehokie** [comment]
Yeah, probably.  This was one of my first node projects... so it could
probably go for a complete re-write at some point
